### ISSUE TITLE
Acompanhamento de frentes

### ISSUE THREAD

**Issue by carlossteinzup** [ZupIT/beagle-docs#280]
- [x] https://github.com/ZupIT/docs-beagle/issues/240 - Frente PJ - Beagle - Danilo Rangel
- [x] https://github.com/ZupIT/docs-beagle/issues/249 - Frente Apps Corporativos - Eduardo Sejas
- [x] https://github.com/ZupIT/docs-beagle/issues/244 - Frente Ciam/RBA

**Comment by carlossteinzup** [comment]
done
